/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedMaintenancesRouteImport } from './routes/_authenticated/maintenances'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated/financials'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaintenancesRoute =
  AuthenticatedMaintenancesRouteImport.update({
    id: '/maintenances',
    path: '/maintenances',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/maintenances': typeof AuthenticatedMaintenancesRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/tenants': typeof AuthenticatedTenantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/maintenances': typeof AuthenticatedMaintenancesRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/tenants': typeof AuthenticatedTenantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/maintenances': typeof AuthenticatedMaintenancesRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contracts'
    | '/dashboard'
    | '/financials'
    | '/maintenances'
    | '/properties'
    | '/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contracts'
    | '/dashboard'
    | '/financials'
    | '/maintenances'
    | '/properties'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/financials'
    | '/_authenticated/maintenances'
    | '/_authenticated/properties'
    | '/_authenticated/tenants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenances': {
      id: '/_authenticated/maintenances'
      path: '/maintenances'
      fullPath: '/maintenances'
      preLoaderRoute: typeof AuthenticatedMaintenancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedMaintenancesRoute: typeof AuthenticatedMaintenancesRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedMaintenancesRoute: AuthenticatedMaintenancesRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
