/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantSetupRouteImport } from './routes/tenant-setup'
import { Route as ManagerSetupRouteImport } from './routes/manager-setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ManagerRouteImport } from './routes/_manager'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedMaintenancesRouteImport } from './routes/_authenticated/maintenances'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated/financials'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedContaCorrenteRouteImport } from './routes/_authenticated/conta-corrente'
import { Route as ManagerManagerIndexRouteImport } from './routes/_manager/manager.index'
import { Route as AuthenticatedTenantIndexRouteImport } from './routes/_authenticated/tenant.index'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as ManagerManagerVistoriasRouteImport } from './routes/_manager/manager.vistorias'
import { Route as ManagerManagerPortaisRouteImport } from './routes/_manager/manager.portais'
import { Route as ManagerManagerMigrarDadosRouteImport } from './routes/_manager/manager.migrar-dados'
import { Route as ManagerManagerIntegracaoRouteImport } from './routes/_manager/manager.integracao'
import { Route as ManagerManagerFinanceiroRouteImport } from './routes/_manager/manager.financeiro'
import { Route as ManagerManagerEquipeRouteImport } from './routes/_manager/manager.equipe'
import { Route as ManagerManagerDimobRouteImport } from './routes/_manager/manager.dimob'
import { Route as ManagerManagerCrmRouteImport } from './routes/_manager/manager.crm'
import { Route as ManagerManagerCarteiraRouteImport } from './routes/_manager/manager.carteira'
import { Route as ManagerManagerAlertasRouteImport } from './routes/_manager/manager.alertas'
import { Route as AuthenticatedTenantManutencoesRouteImport } from './routes/_authenticated/tenant.manutencoes'
import { Route as AuthenticatedTenantFinanceiroRouteImport } from './routes/_authenticated/tenant.financeiro'
import { Route as AuthenticatedTenantContratoRouteImport } from './routes/_authenticated/tenant.contrato'
import { Route as AuthenticatedTenantAlertasRouteImport } from './routes/_authenticated/tenant.alertas'
import { Route as AuthenticatedAdminIntegracoesRouteImport } from './routes/_authenticated/admin.integracoes'
import { Route as ApiPublicListingsXmlRouteImport } from './routes/api/public/listings.xml'
import { Route as ApiPublicHooksSendTenantRemindersRouteImport } from './routes/api/public/hooks/send-tenant-reminders'
import { Route as ApiPublicHooksSendMaintenanceResponseRemindersRouteImport } from './routes/api/public/hooks/send-maintenance-response-reminders'
import { Route as ApiPublicHooksProcessScheduledInvoicesRouteImport } from './routes/api/public/hooks/process-scheduled-invoices'

const TenantSetupRoute = TenantSetupRouteImport.update({
  id: '/tenant-setup',
  path: '/tenant-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSetupRoute = ManagerSetupRouteImport.update({
  id: '/manager-setup',
  path: '/manager-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/_manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMaintenancesRoute =
  AuthenticatedMaintenancesRouteImport.update({
    id: '/maintenances',
    path: '/maintenances',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContaCorrenteRoute =
  AuthenticatedContaCorrenteRouteImport.update({
    id: '/conta-corrente',
    path: '/conta-corrente',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ManagerManagerIndexRoute = ManagerManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => ManagerRoute,
} as any)
const AuthenticatedTenantIndexRoute =
  AuthenticatedTenantIndexRouteImport.update({
    id: '/tenant/',
    path: '/tenant/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerManagerVistoriasRoute = ManagerManagerVistoriasRouteImport.update({
  id: '/manager/vistorias',
  path: '/manager/vistorias',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerManagerPortaisRoute = ManagerManagerPortaisRouteImport.update({
  id: '/manager/portais',
  path: '/manager/portais',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerManagerMigrarDadosRoute =
  ManagerManagerMigrarDadosRouteImport.update({
    id: '/manager/migrar-dados',
    path: '/manager/migrar-dados',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerManagerIntegracaoRoute =
  ManagerManagerIntegracaoRouteImport.update({
    id: '/manager/integracao',
    path: '/manager/integracao',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerManagerFinanceiroRoute =
  ManagerManagerFinanceiroRouteImport.update({
    id: '/manager/financeiro',
    path: '/manager/financeiro',
    getParentRoute: () => ManagerRoute,
  } as any)
const ManagerManagerEquipeRoute = ManagerManagerEquipeRouteImport.update({
  id: '/manager/equipe',
  path: '/manager/equipe',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerManagerDimobRoute = ManagerManagerDimobRouteImport.update({
  id: '/manager/dimob',
  path: '/manager/dimob',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerManagerCrmRoute = ManagerManagerCrmRouteImport.update({
  id: '/manager/crm',
  path: '/manager/crm',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerManagerCarteiraRoute = ManagerManagerCarteiraRouteImport.update({
  id: '/manager/carteira',
  path: '/manager/carteira',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerManagerAlertasRoute = ManagerManagerAlertasRouteImport.update({
  id: '/manager/alertas',
  path: '/manager/alertas',
  getParentRoute: () => ManagerRoute,
} as any)
const AuthenticatedTenantManutencoesRoute =
  AuthenticatedTenantManutencoesRouteImport.update({
    id: '/tenant/manutencoes',
    path: '/tenant/manutencoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantFinanceiroRoute =
  AuthenticatedTenantFinanceiroRouteImport.update({
    id: '/tenant/financeiro',
    path: '/tenant/financeiro',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantContratoRoute =
  AuthenticatedTenantContratoRouteImport.update({
    id: '/tenant/contrato',
    path: '/tenant/contrato',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantAlertasRoute =
  AuthenticatedTenantAlertasRouteImport.update({
    id: '/tenant/alertas',
    path: '/tenant/alertas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIntegracoesRoute =
  AuthenticatedAdminIntegracoesRouteImport.update({
    id: '/admin/integracoes',
    path: '/admin/integracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicListingsXmlRoute = ApiPublicListingsXmlRouteImport.update({
  id: '/api/public/listings/xml',
  path: '/api/public/listings/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSendTenantRemindersRoute =
  ApiPublicHooksSendTenantRemindersRouteImport.update({
    id: '/api/public/hooks/send-tenant-reminders',
    path: '/api/public/hooks/send-tenant-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendMaintenanceResponseRemindersRoute =
  ApiPublicHooksSendMaintenanceResponseRemindersRouteImport.update({
    id: '/api/public/hooks/send-maintenance-response-reminders',
    path: '/api/public/hooks/send-maintenance-response-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessScheduledInvoicesRoute =
  ApiPublicHooksProcessScheduledInvoicesRouteImport.update({
    id: '/api/public/hooks/process-scheduled-invoices',
    path: '/api/public/hooks/process-scheduled-invoices',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/manager-setup': typeof ManagerSetupRoute
  '/tenant-setup': typeof TenantSetupRoute
  '/conta-corrente': typeof AuthenticatedContaCorrenteRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/maintenances': typeof AuthenticatedMaintenancesRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/tenant/alertas': typeof AuthenticatedTenantAlertasRoute
  '/tenant/contrato': typeof AuthenticatedTenantContratoRoute
  '/tenant/financeiro': typeof AuthenticatedTenantFinanceiroRoute
  '/tenant/manutencoes': typeof AuthenticatedTenantManutencoesRoute
  '/manager/alertas': typeof ManagerManagerAlertasRoute
  '/manager/carteira': typeof ManagerManagerCarteiraRoute
  '/manager/crm': typeof ManagerManagerCrmRoute
  '/manager/dimob': typeof ManagerManagerDimobRoute
  '/manager/equipe': typeof ManagerManagerEquipeRoute
  '/manager/financeiro': typeof ManagerManagerFinanceiroRoute
  '/manager/integracao': typeof ManagerManagerIntegracaoRoute
  '/manager/migrar-dados': typeof ManagerManagerMigrarDadosRoute
  '/manager/portais': typeof ManagerManagerPortaisRoute
  '/manager/vistorias': typeof ManagerManagerVistoriasRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/tenant/': typeof AuthenticatedTenantIndexRoute
  '/manager/': typeof ManagerManagerIndexRoute
  '/api/public/hooks/process-scheduled-invoices': typeof ApiPublicHooksProcessScheduledInvoicesRoute
  '/api/public/hooks/send-maintenance-response-reminders': typeof ApiPublicHooksSendMaintenanceResponseRemindersRoute
  '/api/public/hooks/send-tenant-reminders': typeof ApiPublicHooksSendTenantRemindersRoute
  '/api/public/listings/xml': typeof ApiPublicListingsXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/manager-setup': typeof ManagerSetupRoute
  '/tenant-setup': typeof TenantSetupRoute
  '/conta-corrente': typeof AuthenticatedContaCorrenteRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/maintenances': typeof AuthenticatedMaintenancesRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/tenant/alertas': typeof AuthenticatedTenantAlertasRoute
  '/tenant/contrato': typeof AuthenticatedTenantContratoRoute
  '/tenant/financeiro': typeof AuthenticatedTenantFinanceiroRoute
  '/tenant/manutencoes': typeof AuthenticatedTenantManutencoesRoute
  '/manager/alertas': typeof ManagerManagerAlertasRoute
  '/manager/carteira': typeof ManagerManagerCarteiraRoute
  '/manager/crm': typeof ManagerManagerCrmRoute
  '/manager/dimob': typeof ManagerManagerDimobRoute
  '/manager/equipe': typeof ManagerManagerEquipeRoute
  '/manager/financeiro': typeof ManagerManagerFinanceiroRoute
  '/manager/integracao': typeof ManagerManagerIntegracaoRoute
  '/manager/migrar-dados': typeof ManagerManagerMigrarDadosRoute
  '/manager/portais': typeof ManagerManagerPortaisRoute
  '/manager/vistorias': typeof ManagerManagerVistoriasRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/tenant': typeof AuthenticatedTenantIndexRoute
  '/manager': typeof ManagerManagerIndexRoute
  '/api/public/hooks/process-scheduled-invoices': typeof ApiPublicHooksProcessScheduledInvoicesRoute
  '/api/public/hooks/send-maintenance-response-reminders': typeof ApiPublicHooksSendMaintenanceResponseRemindersRoute
  '/api/public/hooks/send-tenant-reminders': typeof ApiPublicHooksSendTenantRemindersRoute
  '/api/public/listings/xml': typeof ApiPublicListingsXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_manager': typeof ManagerRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/manager-setup': typeof ManagerSetupRoute
  '/tenant-setup': typeof TenantSetupRoute
  '/_authenticated/conta-corrente': typeof AuthenticatedContaCorrenteRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/maintenances': typeof AuthenticatedMaintenancesRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/integracoes': typeof AuthenticatedAdminIntegracoesRoute
  '/_authenticated/tenant/alertas': typeof AuthenticatedTenantAlertasRoute
  '/_authenticated/tenant/contrato': typeof AuthenticatedTenantContratoRoute
  '/_authenticated/tenant/financeiro': typeof AuthenticatedTenantFinanceiroRoute
  '/_authenticated/tenant/manutencoes': typeof AuthenticatedTenantManutencoesRoute
  '/_manager/manager/alertas': typeof ManagerManagerAlertasRoute
  '/_manager/manager/carteira': typeof ManagerManagerCarteiraRoute
  '/_manager/manager/crm': typeof ManagerManagerCrmRoute
  '/_manager/manager/dimob': typeof ManagerManagerDimobRoute
  '/_manager/manager/equipe': typeof ManagerManagerEquipeRoute
  '/_manager/manager/financeiro': typeof ManagerManagerFinanceiroRoute
  '/_manager/manager/integracao': typeof ManagerManagerIntegracaoRoute
  '/_manager/manager/migrar-dados': typeof ManagerManagerMigrarDadosRoute
  '/_manager/manager/portais': typeof ManagerManagerPortaisRoute
  '/_manager/manager/vistorias': typeof ManagerManagerVistoriasRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/_authenticated/tenant/': typeof AuthenticatedTenantIndexRoute
  '/_manager/manager/': typeof ManagerManagerIndexRoute
  '/api/public/hooks/process-scheduled-invoices': typeof ApiPublicHooksProcessScheduledInvoicesRoute
  '/api/public/hooks/send-maintenance-response-reminders': typeof ApiPublicHooksSendMaintenanceResponseRemindersRoute
  '/api/public/hooks/send-tenant-reminders': typeof ApiPublicHooksSendTenantRemindersRoute
  '/api/public/listings/xml': typeof ApiPublicListingsXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/manager-setup'
    | '/tenant-setup'
    | '/conta-corrente'
    | '/contracts'
    | '/dashboard'
    | '/financials'
    | '/integrations'
    | '/maintenances'
    | '/properties'
    | '/tenants'
    | '/admin/integracoes'
    | '/tenant/alertas'
    | '/tenant/contrato'
    | '/tenant/financeiro'
    | '/tenant/manutencoes'
    | '/manager/alertas'
    | '/manager/carteira'
    | '/manager/crm'
    | '/manager/dimob'
    | '/manager/equipe'
    | '/manager/financeiro'
    | '/manager/integracao'
    | '/manager/migrar-dados'
    | '/manager/portais'
    | '/manager/vistorias'
    | '/api/public/asaas-webhook'
    | '/tenant/'
    | '/manager/'
    | '/api/public/hooks/process-scheduled-invoices'
    | '/api/public/hooks/send-maintenance-response-reminders'
    | '/api/public/hooks/send-tenant-reminders'
    | '/api/public/listings/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/manager-setup'
    | '/tenant-setup'
    | '/conta-corrente'
    | '/contracts'
    | '/dashboard'
    | '/financials'
    | '/integrations'
    | '/maintenances'
    | '/properties'
    | '/tenants'
    | '/admin/integracoes'
    | '/tenant/alertas'
    | '/tenant/contrato'
    | '/tenant/financeiro'
    | '/tenant/manutencoes'
    | '/manager/alertas'
    | '/manager/carteira'
    | '/manager/crm'
    | '/manager/dimob'
    | '/manager/equipe'
    | '/manager/financeiro'
    | '/manager/integracao'
    | '/manager/migrar-dados'
    | '/manager/portais'
    | '/manager/vistorias'
    | '/api/public/asaas-webhook'
    | '/tenant'
    | '/manager'
    | '/api/public/hooks/process-scheduled-invoices'
    | '/api/public/hooks/send-maintenance-response-reminders'
    | '/api/public/hooks/send-tenant-reminders'
    | '/api/public/listings/xml'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_manager'
    | '/cadastro'
    | '/login'
    | '/manager-setup'
    | '/tenant-setup'
    | '/_authenticated/conta-corrente'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/financials'
    | '/_authenticated/integrations'
    | '/_authenticated/maintenances'
    | '/_authenticated/properties'
    | '/_authenticated/tenants'
    | '/_authenticated/'
    | '/_authenticated/admin/integracoes'
    | '/_authenticated/tenant/alertas'
    | '/_authenticated/tenant/contrato'
    | '/_authenticated/tenant/financeiro'
    | '/_authenticated/tenant/manutencoes'
    | '/_manager/manager/alertas'
    | '/_manager/manager/carteira'
    | '/_manager/manager/crm'
    | '/_manager/manager/dimob'
    | '/_manager/manager/equipe'
    | '/_manager/manager/financeiro'
    | '/_manager/manager/integracao'
    | '/_manager/manager/migrar-dados'
    | '/_manager/manager/portais'
    | '/_manager/manager/vistorias'
    | '/api/public/asaas-webhook'
    | '/_authenticated/tenant/'
    | '/_manager/manager/'
    | '/api/public/hooks/process-scheduled-invoices'
    | '/api/public/hooks/send-maintenance-response-reminders'
    | '/api/public/hooks/send-tenant-reminders'
    | '/api/public/listings/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ManagerSetupRoute: typeof ManagerSetupRoute
  TenantSetupRoute: typeof TenantSetupRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicHooksProcessScheduledInvoicesRoute: typeof ApiPublicHooksProcessScheduledInvoicesRoute
  ApiPublicHooksSendMaintenanceResponseRemindersRoute: typeof ApiPublicHooksSendMaintenanceResponseRemindersRoute
  ApiPublicHooksSendTenantRemindersRoute: typeof ApiPublicHooksSendTenantRemindersRoute
  ApiPublicListingsXmlRoute: typeof ApiPublicListingsXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant-setup': {
      id: '/tenant-setup'
      path: '/tenant-setup'
      fullPath: '/tenant-setup'
      preLoaderRoute: typeof TenantSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-setup': {
      id: '/manager-setup'
      path: '/manager-setup'
      fullPath: '/manager-setup'
      preLoaderRoute: typeof ManagerSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_manager': {
      id: '/_manager'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenances': {
      id: '/_authenticated/maintenances'
      path: '/maintenances'
      fullPath: '/maintenances'
      preLoaderRoute: typeof AuthenticatedMaintenancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/conta-corrente': {
      id: '/_authenticated/conta-corrente'
      path: '/conta-corrente'
      fullPath: '/conta-corrente'
      preLoaderRoute: typeof AuthenticatedContaCorrenteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_manager/manager/': {
      id: '/_manager/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_authenticated/tenant/': {
      id: '/_authenticated/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof AuthenticatedTenantIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_manager/manager/vistorias': {
      id: '/_manager/manager/vistorias'
      path: '/manager/vistorias'
      fullPath: '/manager/vistorias'
      preLoaderRoute: typeof ManagerManagerVistoriasRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/portais': {
      id: '/_manager/manager/portais'
      path: '/manager/portais'
      fullPath: '/manager/portais'
      preLoaderRoute: typeof ManagerManagerPortaisRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/migrar-dados': {
      id: '/_manager/manager/migrar-dados'
      path: '/manager/migrar-dados'
      fullPath: '/manager/migrar-dados'
      preLoaderRoute: typeof ManagerManagerMigrarDadosRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/integracao': {
      id: '/_manager/manager/integracao'
      path: '/manager/integracao'
      fullPath: '/manager/integracao'
      preLoaderRoute: typeof ManagerManagerIntegracaoRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/financeiro': {
      id: '/_manager/manager/financeiro'
      path: '/manager/financeiro'
      fullPath: '/manager/financeiro'
      preLoaderRoute: typeof ManagerManagerFinanceiroRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/equipe': {
      id: '/_manager/manager/equipe'
      path: '/manager/equipe'
      fullPath: '/manager/equipe'
      preLoaderRoute: typeof ManagerManagerEquipeRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/dimob': {
      id: '/_manager/manager/dimob'
      path: '/manager/dimob'
      fullPath: '/manager/dimob'
      preLoaderRoute: typeof ManagerManagerDimobRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/crm': {
      id: '/_manager/manager/crm'
      path: '/manager/crm'
      fullPath: '/manager/crm'
      preLoaderRoute: typeof ManagerManagerCrmRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/carteira': {
      id: '/_manager/manager/carteira'
      path: '/manager/carteira'
      fullPath: '/manager/carteira'
      preLoaderRoute: typeof ManagerManagerCarteiraRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_manager/manager/alertas': {
      id: '/_manager/manager/alertas'
      path: '/manager/alertas'
      fullPath: '/manager/alertas'
      preLoaderRoute: typeof ManagerManagerAlertasRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/_authenticated/tenant/manutencoes': {
      id: '/_authenticated/tenant/manutencoes'
      path: '/tenant/manutencoes'
      fullPath: '/tenant/manutencoes'
      preLoaderRoute: typeof AuthenticatedTenantManutencoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/financeiro': {
      id: '/_authenticated/tenant/financeiro'
      path: '/tenant/financeiro'
      fullPath: '/tenant/financeiro'
      preLoaderRoute: typeof AuthenticatedTenantFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/contrato': {
      id: '/_authenticated/tenant/contrato'
      path: '/tenant/contrato'
      fullPath: '/tenant/contrato'
      preLoaderRoute: typeof AuthenticatedTenantContratoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenant/alertas': {
      id: '/_authenticated/tenant/alertas'
      path: '/tenant/alertas'
      fullPath: '/tenant/alertas'
      preLoaderRoute: typeof AuthenticatedTenantAlertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/integracoes': {
      id: '/_authenticated/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AuthenticatedAdminIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/listings/xml': {
      id: '/api/public/listings/xml'
      path: '/api/public/listings/xml'
      fullPath: '/api/public/listings/xml'
      preLoaderRoute: typeof ApiPublicListingsXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-tenant-reminders': {
      id: '/api/public/hooks/send-tenant-reminders'
      path: '/api/public/hooks/send-tenant-reminders'
      fullPath: '/api/public/hooks/send-tenant-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendTenantRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-maintenance-response-reminders': {
      id: '/api/public/hooks/send-maintenance-response-reminders'
      path: '/api/public/hooks/send-maintenance-response-reminders'
      fullPath: '/api/public/hooks/send-maintenance-response-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendMaintenanceResponseRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-scheduled-invoices': {
      id: '/api/public/hooks/process-scheduled-invoices'
      path: '/api/public/hooks/process-scheduled-invoices'
      fullPath: '/api/public/hooks/process-scheduled-invoices'
      preLoaderRoute: typeof ApiPublicHooksProcessScheduledInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedContaCorrenteRoute: typeof AuthenticatedContaCorrenteRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMaintenancesRoute: typeof AuthenticatedMaintenancesRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminIntegracoesRoute: typeof AuthenticatedAdminIntegracoesRoute
  AuthenticatedTenantAlertasRoute: typeof AuthenticatedTenantAlertasRoute
  AuthenticatedTenantContratoRoute: typeof AuthenticatedTenantContratoRoute
  AuthenticatedTenantFinanceiroRoute: typeof AuthenticatedTenantFinanceiroRoute
  AuthenticatedTenantManutencoesRoute: typeof AuthenticatedTenantManutencoesRoute
  AuthenticatedTenantIndexRoute: typeof AuthenticatedTenantIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContaCorrenteRoute: AuthenticatedContaCorrenteRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMaintenancesRoute: AuthenticatedMaintenancesRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminIntegracoesRoute: AuthenticatedAdminIntegracoesRoute,
  AuthenticatedTenantAlertasRoute: AuthenticatedTenantAlertasRoute,
  AuthenticatedTenantContratoRoute: AuthenticatedTenantContratoRoute,
  AuthenticatedTenantFinanceiroRoute: AuthenticatedTenantFinanceiroRoute,
  AuthenticatedTenantManutencoesRoute: AuthenticatedTenantManutencoesRoute,
  AuthenticatedTenantIndexRoute: AuthenticatedTenantIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ManagerRouteChildren {
  ManagerManagerAlertasRoute: typeof ManagerManagerAlertasRoute
  ManagerManagerCarteiraRoute: typeof ManagerManagerCarteiraRoute
  ManagerManagerCrmRoute: typeof ManagerManagerCrmRoute
  ManagerManagerDimobRoute: typeof ManagerManagerDimobRoute
  ManagerManagerEquipeRoute: typeof ManagerManagerEquipeRoute
  ManagerManagerFinanceiroRoute: typeof ManagerManagerFinanceiroRoute
  ManagerManagerIntegracaoRoute: typeof ManagerManagerIntegracaoRoute
  ManagerManagerMigrarDadosRoute: typeof ManagerManagerMigrarDadosRoute
  ManagerManagerPortaisRoute: typeof ManagerManagerPortaisRoute
  ManagerManagerVistoriasRoute: typeof ManagerManagerVistoriasRoute
  ManagerManagerIndexRoute: typeof ManagerManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerManagerAlertasRoute: ManagerManagerAlertasRoute,
  ManagerManagerCarteiraRoute: ManagerManagerCarteiraRoute,
  ManagerManagerCrmRoute: ManagerManagerCrmRoute,
  ManagerManagerDimobRoute: ManagerManagerDimobRoute,
  ManagerManagerEquipeRoute: ManagerManagerEquipeRoute,
  ManagerManagerFinanceiroRoute: ManagerManagerFinanceiroRoute,
  ManagerManagerIntegracaoRoute: ManagerManagerIntegracaoRoute,
  ManagerManagerMigrarDadosRoute: ManagerManagerMigrarDadosRoute,
  ManagerManagerPortaisRoute: ManagerManagerPortaisRoute,
  ManagerManagerVistoriasRoute: ManagerManagerVistoriasRoute,
  ManagerManagerIndexRoute: ManagerManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ManagerSetupRoute: ManagerSetupRoute,
  TenantSetupRoute: TenantSetupRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicHooksProcessScheduledInvoicesRoute:
    ApiPublicHooksProcessScheduledInvoicesRoute,
  ApiPublicHooksSendMaintenanceResponseRemindersRoute:
    ApiPublicHooksSendMaintenanceResponseRemindersRoute,
  ApiPublicHooksSendTenantRemindersRoute:
    ApiPublicHooksSendTenantRemindersRoute,
  ApiPublicListingsXmlRoute: ApiPublicListingsXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
